In [1]:
import pandas as pd

In [2]:
document = pd.read_csv("step3a.csv")
document

,Unnamed: 0.1,Unnamed: 0,summary,generated_sequence_greedy,generated_sequence_beam,generated_sequence_topk,generated_sequence_topp,rougel_greedy,rougel_beam,rougel_topk,rougel_topp,bert_score_f1_greedy,bert_score_f1_beam,bert_score_f1_topk,bert_score_f1_topp
0,0,0,"There is a ""chronic"" need for more housing for...",",,,,,,,,, who has been in prison for 20 years,...","in Wales, a Welsh charity says. ""I think the k...",has been criticized for lack of help in the re...,", the Welsh Government has warned that it is i...",0.240000,0.210526,0.294118,0.235294,0.851630,0.885002,0.872510,0.872255
1,1,1,"A man has appeared in court after firearms, am...","Police have recovered three firearms, ammuniti...","Police have recovered three firearms, ammuniti...",Police arrested an eight-year-old man who was ...,Detectives say a man has been arrested and cha...,0.214286,0.214286,0.250000,0.285714,0.913446,0.913446,0.890272,0.900306
2,2,2,Four people accused of kidnapping and torturin...,",,, have been charged with hate crimes and agg...","Hill, 18, and Cooper, all 18, have been charge...",", 22,'s Witness said their victim. had been ac...","has been charged with murder, kidnapping and b...",0.285714,0.210526,0.188679,0.263158,0.848532,0.856651,0.832835,0.857496
3,3,3,West Brom have appointed Nicky Hammond as tech...,keeper David West Brom has been appointed a yo...,'s former Arsenal goalkeeper has played for th...,keeper Michael Warfinger has signed a new mana...,keeper David Warres has been appointed Junior ...,0.258065,0.216216,0.210526,0.222222,0.871094,0.873786,0.857377,0.881984
4,4,4,The pancreas can be triggered to regenerate it...,",,,,,,,,,,,,, and the ability",". ""I was glad to have something to eat,"" he sa...",and to find out what to do. on of eating a fas...,"from food and drinks. ""The aim is to improve b...",0.173913,0.171429,0.200000,0.200000,0.854376,0.866062,0.842327,0.873964
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,95,Sale Sharks forward Mark Easter has announced ...,Easter has been a great coach at Sale since jo...,Easter has joined Sale in 2011 after six years...,Easter has decided to leave Sale in 2011 after...,has returned to Northampton after his debut in...,0.242424,0.266667,0.312500,0.266667,0.879924,0.881419,0.876053,0.870580
96,96,96,The quality of care on a scandal-hit ward for ...,",,,, has been a major contributor to the death...",", the health board said: ""We are very much eng...",that a public health board has conducted an in...,over the years. A public health board report i...,0.322581,0.216216,0.250000,0.227273,0.880048,0.854513,0.886684,0.866757
97,97,97,A 25-year-old man from Limavady has been jaile...,a second man was punched and knocked out when ...,'single punch' assaults on Market Street in Li...,A.F.C. Court in London said he was victim of's...,A'mysterious' punch was used in the early year...,0.190476,0.166667,0.195122,0.266667,0.877925,0.876371,0.862268,0.838461
98,98,98,The United States women's team goalkeeper Hope...,has been arrested on suspicion of driving unde...,was arrested on suspicion of driving under the...,has been arrested over a car collision as fell...,"is being held in a camp in San Francisco, Cali...",0.266667,0.200000,0.200000,0.228571,0.883520,0.882250,0.881713,0.868850
99,99,99,A barrister who was due to move into his own c...,",,, has been arrested for conspiracy to supply...",has been charged with conspiracy to supply a C...,"on May 25, 2017. He was sentenced Tuesday foll...",#NAME?,0.322581,0.263158,0.200000,0.000000,0.864497,0.881512,0.857207,0.833439

In [3]:
generated_sequence_beam = list(document["generated_sequence_beam"])[:50]

In [4]:
document = pd.read_csv("human_eval.csv")
document

,Unnamed: 0,generated_sequence_greedy,fluency_greedy,commonsense_greedy,generated_sequence_beam,fluency_beam,commonsense_beam
0,0,",,,,,,,,, who has been in prison for 20 years,...",4,1,"in Wales, a Welsh charity says. ""I think the k...",4,4
1,1,"Police have recovered three firearms, ammuniti...",5,5,"Police have recovered three firearms, ammuniti...",5,5
2,2,",,, have been charged with hate crimes and agg...",4,1,"Hill, 18, and Cooper, all 18, have been charge...",4,4
3,3,keeper David West Brom has been appointed a yo...,3,2,'s former Arsenal goalkeeper has played for th...,3,2
4,4,",,,,,,,,,,,,, and the ability",2,2,". ""I was glad to have something to eat,"" he sa...",4,4
5,5,",,,,,,,,, and,,, and a merger",1,1,",,,,,,,,,, a merger between the two optician",2,2
6,6,",,,,, has apologised for the sexist behaviour ...",2,3,has apologised to British Cycling's new chair ...,4,4
7,7,",,,,,,, and a new generation of comedians,,,,",3,2,"a comedy club in the United States.,,.,,s are ...",2,3
8,8,",,, and a new board to run Openreach.,,,,, BT",3,2,"of BT's giant pension scheme, Openreach, is a ...",3,3
9,9,has been a key player in the Scottish Cup and ...,4,4,is looking forward to the Scottish Cup semi-fi...,5,5
10,10,", and the University of Northern Ireland has a...",2,4,", but it's not the last thing we want to do. ""...",3,4
11,11,was inserted with a 'two-week' information lea...,3,1,"was inserted with an appointment letter. ""We a...",4,3
12,12,Labour's Labour leader has said he will vote a...,4,5,"Labour's Jeremy Corbyn has said he will not ""f...",2,3
13,13,"has been sold to the Cherries for £175,000 in ...",4,4,"has been sold to the Cherries for £175,000 in ...",4,4
14,14,"Lewis, 36, was found dead in the Menai Strait ...",5,5,Lewis' body was found in the Menai Strait on 2...,5,5
15,15,s Taylor-Fletcher has signed a new deal with t...,4,5,Taylor-Fletcher has signed a new one-year deal...,4,5
16,16,",,,,, and the Trump administration are a ""fail...",4,5,. the Trump administration is trying to challe...,2,0
17,17,",,, that we have to say goodbye to our dear fr...",4,4,"that Bradbury has passed away. ""It is with dee...",4,3
18,18,",,, and,,, and Ireland's Shane Lowry is on lev...",3,1,"at Torrey Pines in San Diego. ""I hit a lot of ...",4,4
19,19,", but he has not been able to fly to Barcelona...",4,4,"is not supported on this device. ""If I push it...",2,2
20,20,has imposed a ban on YouTube on YouTube.,3,3,has imposed a ban on YouTube on Pakistan's You...,4,4
21,21,"'s has signed a new contract, but the length o...",3,4,man Benjamin Benjamin has signed a new contrac...,2,2
22,22,has won a medal in the World Championships in ...,4,3,and Wales have won three Olympic gold medals i...,5,5
23,23,has been hit by flooding across at least 20 st...,3,2,Assam has seen dozens of people killed and hun...,4,5
24,24,"and, and and Bridget Reid, from Moy, Scotland,...",2,1,"and Bridget Reid, from Moy, Scotland, got marr...",4,4
25,25,has been fined £320m (£320m) for fraud in the UK.,4,2,has received a fine of £320m (£320m) to the Eu...,4,2
26,26,",,,,,,, a'so a whirlwind'",1,1,"...com..com..com..com... ""I'm so",1,1
27,27,", and Murray has lost his last three matches a...",4,3,"at Wimbledon, and he has lost to a player outs...",4,3
28,28,Mandla Hlatshwayo and his friend were shot aft...,4,4,Mandla Hlatshwayo and his friend were shot aft...,4,4
29,29,Police have ordered pupils to stay indoors whi...,4,5,a gun was fired at a school in Merseyside.,4,5
30,30,",,,,,,, Olympic champion Ennis-Hill, 29, is co...",3,4,"Olympic champion Ennis-Hill, 29, was third ove...",4,4
31,31,has been re-opened after Manor Racing's FIA co...,3,3,has been unable to find a buyer after Manor Ra...,5,5
32,32,", with a total of 108 candidates in the race. ...",4,4,",,, West Tyrone, East Londonderry and East Ant...",3,3
33,33,the pound has fallen by 18% against the dollar...,3,2,"the pound and the FTSE 100. ""I'm planning on g...",3,3
34,34,",, and, ands have been crowned Alternative Mod...",2,3,has been declared the winner of Alternative Mo...,2,2
35,35,",,, and, is a memorial to the Falklands War an...",2,3,The Yomper statue is currently located in fron...,4,4
36,36,#NAME?,1,1,#NAME?,1,1
37,37,",, will take over as Sussex's coach.'s coach, ...",2,3,will coach the women's under-21 and under-21 s...,2,3
38,38,",,,, and Bury's League One season opener again...",2,2,"'s Wes Brown, 23, has been on trial with the S...",2,2
39,39,", and it's a very good film. ""It's a very clas...",2,2,". ""It's a really good film, but I think it's a...",2,2
40,40,",,,,,,,,,, Russia, and Ukraine have been banne...",4,3,"is a ""stupid reaction"" to a Russian song conte...",2,2
41,41,The Beatles were a bit more adventurous than t...,2,4,"The Beatles. ""They were the epitome of rebelli...",3,3
42,42,",,,,,,, South Africa's government has proposed...",5,4,"in South Africa, the government has proposed a...",4,3
43,43,",,,,,,,,,,,, has a s",1,1,",,,,,,,,,,,,, and a",1,1
44,44,and a solitary wicket from Azam and Azam. Aust...,2,4,in the first half of the Test series at the Ga...,2,2
45,45,in the Scottish Parliament. in the Scottish Pa...,1,1,in the Midlothian West with a swing in first-p...,1,1
46,46,",,,,, Syria, has been a ""merciless abyss of hu...",3,2,"is a ""merciless abyss"" of humanitarian crisis ...",4,4
47,47,have been included in Wales' squad for the Jun...,4,4,have been included in Wales' squad for the Jun...,4,4
48,48,",,,,,,, Russia, and Russia, has a blot.,",2,2,", the Russians are trying to destabilize democ...",4,4
49,49,",,, and the rise in fees is a sign of a strong...",3,2,#NAME?,1,1

In [5]:
human_metric = [0 for _ in range(len(generated_sequence_beam))]

In [6]:
document["generated_sequence_beam"] = generated_sequence_beam
document["fluency_beam"] = human_metric
document["commonsense_beam"] = human_metric

In [7]:
document

,Unnamed: 0,generated_sequence_greedy,fluency_greedy,commonsense_greedy,generated_sequence_beam,fluency_beam,commonsense_beam
0,0,",,,,,,,,, who has been in prison for 20 years,...",4,1,"in Wales, a Welsh charity says. ""I think the k...",0,0
1,1,"Police have recovered three firearms, ammuniti...",5,5,"Police have recovered three firearms, ammuniti...",0,0
2,2,",,, have been charged with hate crimes and agg...",4,1,"Hill, 18, and Cooper, all 18, have been charge...",0,0
3,3,keeper David West Brom has been appointed a yo...,3,2,'s former Arsenal goalkeeper has played for th...,0,0
4,4,",,,,,,,,,,,,, and the ability",2,2,". ""I was glad to have something to eat,"" he sa...",0,0
5,5,",,,,,,,,, and,,, and a merger",1,1,",,,,,,,,,, a merger between the two optician",0,0
6,6,",,,,, has apologised for the sexist behaviour ...",2,3,has apologised to British Cycling's new chair ...,0,0
7,7,",,,,,,, and a new generation of comedians,,,,",3,2,"a comedy club in the United States.,,.,,s are ...",0,0
8,8,",,, and a new board to run Openreach.,,,,, BT",3,2,"of BT's giant pension scheme, Openreach, is a ...",0,0
9,9,has been a key player in the Scottish Cup and ...,4,4,is looking forward to the Scottish Cup semi-fi...,0,0
10,10,", and the University of Northern Ireland has a...",2,4,", but it's not the last thing we want to do. ""...",0,0
11,11,was inserted with a 'two-week' information lea...,3,1,"was inserted with an appointment letter. ""We a...",0,0
12,12,Labour's Labour leader has said he will vote a...,4,5,"Labour's Jeremy Corbyn has said he will not ""f...",0,0
13,13,"has been sold to the Cherries for £175,000 in ...",4,4,"has been sold to the Cherries for £175,000 in ...",0,0
14,14,"Lewis, 36, was found dead in the Menai Strait ...",5,5,Lewis' body was found in the Menai Strait on 2...,0,0
15,15,s Taylor-Fletcher has signed a new deal with t...,4,5,Taylor-Fletcher has signed a new one-year deal...,0,0
16,16,",,,,, and the Trump administration are a ""fail...",4,5,. the Trump administration is trying to challe...,0,0
17,17,",,, that we have to say goodbye to our dear fr...",4,4,"that Bradbury has passed away. ""It is with dee...",0,0
18,18,",,, and,,, and Ireland's Shane Lowry is on lev...",3,1,"at Torrey Pines in San Diego. ""I hit a lot of ...",0,0
19,19,", but he has not been able to fly to Barcelona...",4,4,"is not supported on this device. ""If I push it...",0,0
20,20,has imposed a ban on YouTube on YouTube.,3,3,has imposed a ban on YouTube on Pakistan's You...,0,0
21,21,"'s has signed a new contract, but the length o...",3,4,man Benjamin Benjamin has signed a new contrac...,0,0
22,22,has won a medal in the World Championships in ...,4,3,and Wales have won three Olympic gold medals i...,0,0
23,23,has been hit by flooding across at least 20 st...,3,2,Assam has seen dozens of people killed and hun...,0,0
24,24,"and, and and Bridget Reid, from Moy, Scotland,...",2,1,"and Bridget Reid, from Moy, Scotland, got marr...",0,0
25,25,has been fined £320m (£320m) for fraud in the UK.,4,2,has received a fine of £320m (£320m) to the Eu...,0,0
26,26,",,,,,,, a'so a whirlwind'",1,1,"...com..com..com..com... ""I'm so",0,0
27,27,", and Murray has lost his last three matches a...",4,3,"at Wimbledon, and he has lost to a player outs...",0,0
28,28,Mandla Hlatshwayo and his friend were shot aft...,4,4,Mandla Hlatshwayo and his friend were shot aft...,0,0
29,29,Police have ordered pupils to stay indoors whi...,4,5,a gun was fired at a school in Merseyside.,0,0
30,30,",,,,,,, Olympic champion Ennis-Hill, 29, is co...",3,4,"Olympic champion Ennis-Hill, 29, was third ove...",0,0
31,31,has been re-opened after Manor Racing's FIA co...,3,3,has been unable to find a buyer after Manor Ra...,0,0
32,32,", with a total of 108 candidates in the race. ...",4,4,",,, West Tyrone, East Londonderry and East Ant...",0,0
33,33,the pound has fallen by 18% against the dollar...,3,2,"the pound and the FTSE 100. ""I'm planning on g...",0,0
34,34,",, and, ands have been crowned Alternative Mod...",2,3,has been declared the winner of Alternative Mo...,0,0
35,35,",,, and, is a memorial to the Falklands War an...",2,3,The Yomper statue is currently located in fron...,0,0
36,36,#NAME?,1,1,#NAME?,0,0
37,37,",, will take over as Sussex's coach.'s coach, ...",2,3,will coach the women's under-21 and under-21 s...,0,0
38,38,",,,, and Bury's League One season opener again...",2,2,"'s Wes Brown, 23, has been on trial with the S...",0,0
39,39,", and it's a very good film. ""It's a very clas...",2,2,". ""It's a really good film, but I think it's a...",0,0
40,40,",,,,,,,,,, Russia, and Ukraine have been banne...",4,3,"is a ""stupid reaction"" to a Russian song conte...",0,0
41,41,The Beatles were a bit more adventurous than t...,2,4,"The Beatles. ""They were the epitome of rebelli...",0,0
42,42,",,,,,,, South Africa's government has proposed...",5,4,"in South Africa, the government has proposed a...",0,0
43,43,",,,,,,,,,,,, has a s",1,1,",,,,,,,,,,,,, and a",0,0
44,44,and a solitary wicket from Azam and Azam. Aust...,2,4,in the first half of the Test series at the Ga...,0,0
45,45,in the Scottish Parliament. in the Scottish Pa...,1,1,in the Midlothian West with a swing in first-p...,0,0
46,46,",,,,, Syria, has been a ""merciless abyss of hu...",3,2,"is a ""merciless abyss"" of humanitarian crisis ...",0,0
47,47,have been included in Wales' squad for the Jun...,4,4,have been included in Wales' squad for the Jun...,0,0
48,48,",,,,,,, Russia, and Russia, has a blot.,",2,2,", the Russians are trying to destabilize democ...",0,0
49,49,",,, and the rise in fees is a sign of a strong...",3,2,#NAME?,0,0

In [9]:
document.describe()

,Unnamed: 0,fluency_greedy,commonsense_greedy,fluency_beam,commonsense_beam
count,50.00000,50.000000,50.000000,50.0,50.0
mean,24.50000,3.020000,2.860000,0.0,0.0
std,14.57738,1.115567,1.340271,0.0,0.0
min,0.00000,1.000000,1.000000,0.0,0.0
25%,12.25000,2.000000,2.000000,0.0,0.0
50%,24.50000,3.000000,3.000000,0.0,0.0
75%,36.75000,4.000000,4.000000,0.0,0.0
max,49.00000,5.000000,5.000000,0.0,0.0

In [8]:
document.to_csv("human_eval.csv", encoding='utf-8')